name: Pipeline CI con Cypress
run-name: Push by @${{ github.actor }}
on:
    [push, pull_request]
jobs:
    cypress-run:
        runs-on: ubuntu-latest
        
        steps:
            - name: Hacer checkout del código
              uses: actions/checkout@v6
            
            - name: Setear Node.js
              uses: actions/setup-node@v6
              with:
                node-version: "24"
                cache: "npm"

            - name: Ejecutar tests de Cypress
              uses: cypress-io/github-action@v6
              env:
                NEXT_PUBLIC_E2E_MODE: "true"
              with:
                build: npm run build
                start: npm run start
                wait-on: "http://localhost:3000"
                wait-on-timeout: 120
                spec: cypress/e2e/**/*.cy.js
            
            - name: Guardar reporte HTML de Mochawesome
              if: always()
              uses: actions/upload-artifact@v4
              with:
                name: cypress-mochawesome-report
                path: cypress/reports/html
                retention-days: 7
            
            - name: Guardar screenshots en caso de fallos
              if: failure()
              uses: actions/upload-artifact@v4
              with:
                name: cypress-screenshots
                path: cypress/screenshots
                retention-days: 7
            
            - name: Guardar videos en caso de fallos
              if: failure()
              uses: actions/upload-artifact@v4
              with:
                name: cypress-videos
                path: cypress/videos
                retention-days: 7
